# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: Node.js CI

# on:
#     push:
#         branches: [main]
#     pull_request:
#         branches: [main]

# jobs:
#     build:
#         runs-on: ubuntu-latest

#         strategy:
#             matrix:
#                 node-version: [14.x]
#                 # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#         steps:
#             - uses: actions/checkout@v2
#             - name: Use Node.js ${{ matrix.node-version }}
#               uses: actions/setup-node@v1
#               with:
#                   node-version: ${{ matrix.node-version }}
#             - name: npm install, build, test
#               working-directory: ./server
#               env:
#                   NODE_ENV: test
#                   PORT: 5000
#                   BASE_URL: http://localhost:5000/api
#                   ACCESS_TOKEN_SECRET: dfmgsdfoiuyhw456s90tdgbhusdfgkbhjsfgnhb
#                   ACCESS_TOKEN_LIFE: 1
#                   ACCESS_TOKEN_NAME: accessToken
#                   REFRESH_TOKEN_SECRET: rkhbndfgoihu346097u4e56dtrhkjdbnfxgsktjhgbwik34j5tygwk45
#                   REFRESH_TOKEN_LIFE: 300
#                   REFRESH_TOKEN_NAME: refreshToken
#               run: |
#                   npm ci
#                   npm run build --if-present
#                   npm test
